name: security-Quality scanning.

on:
  push:
    branches:
      -  All
 # pull_request:
 #   branches: [ "main", ]
  
jobs:
  secret-scan:
    name: Secret Scan with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          scan-args: --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}

