name: security-Quality scanning.

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", ]
  

jobs:
  secret-scan:
    name: Secret Scan with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

